include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    always_use_package_imports: false
    prefer_relative_imports: true
    avoid_print: true
    sort_constructors_first: true
    use_super_parameters: true
